service: naver-playground
useDotenv: true

plugins:
    - serverless-webpack
    - serverless-dotenv-plugin
custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules: true
provider:
    name: aws
    runtime: nodejs14.x
    stage: staging
    region: ${opt:region, 'ap-northeast-1'}
    memorySize: 128
    timeout: 15
    profile: mbt
    logRetentionInDays: 90
    logs:
        httpApi: true
    httpApi:
        cors: true

package:
    individually: false
    exclude:
        - package.json
        - node_modules/**
        - tests/**
        - public/**
        - scripts/**
        - .gitignore
        - .git/**

functions:
    app:
        handler: src/handler.handler
        events:
            - httpApi:
                  path: '/{proxy+}'
                  method: '*'
